---
stages:
  - test

pre-commit:
  stage: test
  image: python:latest
  variables:
    PIP_CACHE_DIR: $CI_PROJECT_DIR/.cache/pip
    PRE_COMMIT_HOME: $CI_PROJECT_DIR/.cache/pre-commit
  cache:
    paths:
      - $CI_PROJECT_DIR/.cache/pip
      - $CI_PROJECT_DIR/.cache/pre-commit
  before_script:
    - pip3 install pre-commit
  script:
    - pre-commit run --all --color=always --show-diff-on-failure
