---
- name: Deploy funkwhale systemd services
  ansible.builtin.template:
    src: systemd/funkwhale-{{ item }}.service.j2
    dest: /etc/systemd/system/{{ funkwhale_instance_id }}-{{ item }}.service
    mode: 0644
  with_items:
    - beat
    - server
    - worker
  notify: Restart funkwhale

- name: Deploy funkwhale systemd target
  ansible.builtin.template:
    src: systemd/funkwhale.target.j2
    dest: /etc/systemd/system/{{ funkwhale_instance_id }}.target
    mode: 0644
  notify: Restart funkwhale

- name: Start and enable funkwhale services
  ansible.builtin.systemd:
    name: "{{ item }}"
    state: started
    enabled: true
    daemon_reload: true
  with_items:
    - "{{ funkwhale_instance_id }}-beat.service"
    - "{{ funkwhale_instance_id }}-server.service"
    - "{{ funkwhale_instance_id }}-worker.service"
    - "{{ funkwhale_instance_id }}.target"
  notify: Restart funkwhale
