---
dependency:
  name: galaxy

driver:
  name: podman

platforms:
  - name: instance
    image: ${MOLECULE_IMAGE:-debian:bullseye}
    dockerfile: Dockerfile.j2
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    override_command: false
    systemd: always
    published_ports:
      - 8080:80

provisioner:
  name: ansible
  env:
    ANSIBLE_FORCE_COLOR: true
    ANSIBLE_PIPELINING: true

verifier:
  name: ansible
