name: CI

on:
  push:
    tags: ["v*.*.*"]
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  pre-commit:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - uses: pre-commit/action@v3.0.0

  test:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        image:
          - ubuntu:focal
          - debian:bullseye

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - uses: actions/cache@v3
        with:
          path: |
            ~/.ansible/collections
            ~/.ansible/roles
            ~/.cache/ansible-compat
          key: ${{ runner.os }}-ansible-${{ hashFiles('**/requirements.yml') }}
          restore-keys: |
            ${{ runner.os }}-ansible-

      - run: make install
      - run: make test
        env:
          PY_COLORS: true
          ANSIBLE_FORCE_COLOR: true
          MOLECULE_IMAGE: ${{ matrix.image }}
